### ISSUE TITLE
'NoneType' object is not callable when trying to setup the project

### ISSUE THREAD

**Issue by Bergrebell** [DARIAH-DE/TopicsExplorer#132]
i am trying to setup the project using python 3.6.15.

when running `pipenv install` i get the following error message:

```
(TopicsExplorer-2.0) ➜  TopicsExplorer-2.0 pipenv install
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Building requirements...
Traceback (most recent call last):
  File "/Users/xyz/.pyenv/versions/3.6.15/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/cli/options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/cli/command.py", line 241, in install
    site_packages=state.site_packages,
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/core.py", line 2102, in do_install
    keep_outdated=keep_outdated,
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/core.py", line 1332, in do_init
    pypi_mirror=pypi_mirror,
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/core.py", line 1132, in do_lock
    keep_outdated=keep_outdated,
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/utils/resolver.py", line 1003, in venv_resolve_deps
    deps = convert_deps_to_pip(deps, project, r=False, include_index=True)
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/utils/dependencies.py", line 258, in convert_deps_to_pip
    req = new_dep.as_line(sources=indexes if include_index else None).strip()
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2795, in as_line
    assert self.line_instance is not None
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2553, in line_instance
    self.line_instance = self.get_line_instance()
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2547, in get_line_instance
    return Line(line)
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 171, in __init__
    self.parse()
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1289, in parse
    self.parse_extras()
  File "/Users/xyz/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 577, in parse_extras
    self.line, extras = pip_shims.shims._strip_extras(self.line)
TypeError: 'NoneType' object is not callable
```

any ideas why this is happening?

**Comment by severinsimmler** [comment]
Fixed via https://github.com/DARIAH-DE/TopicsExplorer/commit/a76d865cc2d3f1f4a3c34494a9c28bb7968cef5e.
