### ISSUE TITLE
Installing from source

### ISSUE THREAD

**Issue by alvaroceb** [DARIAH-DE/TopicsExplorer#134]
I am trying to install TopicsExplorer2.0 on a Mac 12.0.1. Following instructions, I did try to install the application from source. I have Python3.12, so I did actualize the pipfile ([requires] python_version = "3.12”). I keep getting this kind of error message, apparently with a problem in dependencies:  

Last login: Sat Jan 13 14:27:30 on ttys000
ceballos@Air-de-Alvaro ~ % find ~/Library/Python/3.12 -name pipenv
/Users/ceballos/Library/Python/3.12/bin/pipenv
/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv
ceballos@Air-de-Alvaro ~ % export PATH=$HOME/Library/Python/3.12/bin:$PATH
ceballos@Air-de-Alvaro ~ % pipenv --version
pipenv, version 2023.11.15
ceballos@Air-de-Alvaro ~ % cd /Applications/TopicsExplorer-2.0                 
ceballos@Air-de-Alvaro TopicsExplorer-2.0 % pipenv install
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠸ Locking...False
⠸ Locking...ERROR:pip.subprocessor:Getting requirements to build wheel exited with 1
[ResolutionFailure]:   File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/resolver.py", line 645, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/resolver.py", line 612, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:       ^^^^^^^^
[ResolutionFailure]:   File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/resolver.py", line 592, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:       ^^^^^^^^^^^^^
[ResolutionFailure]:   File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/utils/resolver.py", line 908, in resolve_deps
[ResolutionFailure]:       results, hashes, internal_resolver = actually_resolve_deps(
[ResolutionFailure]:       ^^^^^^^^^^^^^^^^^^^^^^
[ResolutionFailure]:   File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/utils/resolver.py", line 681, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/utils/resolver.py", line 442, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Getting requirements to build wheel exited with 1

Traceback (most recent call last):
  File "/Users/ceballos/Library/Python/3.12/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/cli/command.py", line 209, in install
    do_install(
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/routines/install.py", line 164, in do_install
    do_init(
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/routines/install.py", line 672, in do_init
    do_lock(
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/routines/lock.py", line 65, in do_lock
    venv_resolve_deps(
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/utils/resolver.py", line 849, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ceballos/Library/Python/3.12/lib/python/site-packages/pipenv/utils/resolver.py", line 718, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!

Thank you for your help!

**Comment by severinsimmler** [comment]
Hi @alvaroceb, thank you for reporting this issue. I suspect you are using an outdated version. We replaced Pipenv with Poetry some time ago. Please try pulling the latest changes from the master branch and run `poetry install` to install dependencies.
