### ISSUE TITLE
open external links in default browser

### ISSUE THREAD

**Issue by MHuberFaust** [DARIAH-DE/TopicsExplorer#14]
will try https://github.com/electron/electron/issues/1344

**Comment by MHuberFaust** [comment]
just copied it to main.js and results in following error:
App threw an error during load
TypeError: "listener" argument must be a function
    at _addListener (events.js:219:11)
    at App.addListener (events.js:279:10)
    at Object.<anonymous> (/Users/MHuber/git/TopicsExplorer/main.js:7:5)
    at Object.<anonymous> (/Users/MHuber/git/TopicsExplorer/main.js:51:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:283:12)

An alternative would be to use node-open (https://github.com/pwnall/node-open), although it's another dependency...

Thoughts?

**Comment by severinsimmler** [comment]
Using the PyQt WebEngine:
https://stackoverflow.com/questions/3188513/catch-link-clicks-in-qtwebview-and-open-in-default-browser

**Comment by MHuberFaust** [comment]
http://doc.qt.io/qt-5/qlabel.html#openExternalLinks-prop

**Comment by severinsimmler** [comment]
https://github.com/smoqadam/PyFladesk/blob/master/pyfladesk/__init__.py
