### ISSUE TITLE
add loading bar / logging

### ISSUE THREAD

**Issue by MHuberFaust** [DARIAH-DE/TopicsExplorer#5]
create loading bar or sth comparable. Best way is to pipe python logging to flask.

**Comment by severinsimmler** [comment]
Will implement [this](https://stackoverflow.com/questions/31948285/display-data-streamed-from-a-flask-view-as-it-updates/31951077#31951077) asap.

**Comment by severinsimmler** [comment]
Still to do: write logging (*also* from third party libraries) to a file.

See also [this](https://gist.github.com/ibeex/3257877).

**Comment by MHuberFaust** [comment]
on Chrome:
Traceback (most recent call last):
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 260, in execute
    for data in application_iter:
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/werkzeug/wsgi.py", line 870, in __next__
    return self._next()
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
    for item in iterable:
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/flask/helpers.py", line 130, in generator
    for item in gen:
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1271, in __next__
    return self._next()
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1045, in generate
    yield self.environment.handle_exception(exc_info, True)
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/MHuber/git/TopicsExplorer/templates/modeling.html", line 55, in top-level template code
    {% for info_1, info_2, info_3, info_4, info_5 in logging %}
  File "/Users/MHuber/git/TopicsExplorer/webapp.py", line 87, in create_model
    flash("Hallo")
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/flask/helpers.py", line 387, in flash
    session['_flashes'] = flashes
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/werkzeug/local.py", line 350, in __setitem__
    self._get_current_object()[key] = value
  File "/Users/MHuber/git/TopicsExplorer/venv/lib/python3.5/site-packages/flask/sessions.py", line 130, in _fail
    raise RuntimeError('The session is unavailable because no secret '

**Comment by severinsimmler** [comment]
Finally done.
